# .streamlit/config.toml

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[client]
toolbarMode = "auto"

[theme]
base="dark"
primaryColor="#00c3ff"
backgroundColor="#0E1117"
secondaryBackgroundColor="#1C1F26"
textColor="#FAFAFA"
font="sans serif"
